#!/usr/bin/env bash
# Yoohoo — Post-Terraform Server Provisioning
#
# Runs once after `terraform apply` to fully set up the application.
# Bridges the gap between "VPS exists" and "app is running".
#
# Non-interactive mode (all config via env vars):
#   DOMAIN=yoohoo.nl \
#   ADMIN_EMAIL=admin@yoohoo.nl \
#   ADMIN_PASSWORD='StrongPass123!' \
#   GHCR_TOKEN=ghp_... \
#   REPO_URL=https://github.com/rafaelakopian/yoohoo.git \
#     bash scripts/provision/setup.sh
#
# Interactive mode (prompts for missing values):
#   bash scripts/provision/setup.sh
set -euo pipefail

# ─── Colors ───
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[SETUP]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
fail() { echo -e "${RED}[FAIL]${NC} $1"; exit 1; }

APP_DIR="/opt/yoohoo"
SECRETS_DIR="$APP_DIR/secrets"

# ─── Step 0: Verify cloud-init completed ───
log "Checking cloud-init status..."
if command -v cloud-init &>/dev/null; then
  cloud-init status --wait || warn "cloud-init not complete or not available"
fi

# ─── Step 1: Collect configuration ───
prompt_if_empty() {
  local var_name=$1
  local prompt_text=$2
  local is_secret=${3:-false}
  local current_val="${!var_name:-}"

  if [ -z "$current_val" ]; then
    if [ "$is_secret" = "true" ]; then
      read -sp "$prompt_text: " current_val
      echo
    else
      read -p "$prompt_text: " current_val
    fi
    eval "$var_name='$current_val'"
  fi

  if [ -z "$current_val" ]; then
    fail "$var_name is required"
  fi
}

prompt_if_empty DOMAIN "Domain name (e.g., yoohoo.nl)"
prompt_if_empty ADMIN_EMAIL "Admin email"
prompt_if_empty ADMIN_PASSWORD "Admin password" true
prompt_if_empty GHCR_TOKEN "GHCR token (read:packages)" true
REPO_URL="${REPO_URL:-https://github.com/rafaelakopian/yoohoo.git}"

# ─── Step 2: Clone repository ───
if [ -d "$APP_DIR/.git" ]; then
  log "Repository already cloned — pulling latest..."
  cd "$APP_DIR"
  git pull origin main
else
  log "Cloning repository..."
  git clone "$REPO_URL" "$APP_DIR"
  cd "$APP_DIR"
fi

# ─── Step 3: Generate .env with random secrets ───
if [ -f "$APP_DIR/.env" ]; then
  warn ".env already exists — skipping generation"
else
  log "Generating .env with random secrets..."
  SECRET_KEY=$(openssl rand -base64 32)
  JWT_SECRET=$(openssl rand -base64 32)
  PG_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=')
  PG_APP_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=')
  GRAFANA_PASSWORD=$(openssl rand -base64 16 | tr -d '/+=')

  cat > "$APP_DIR/.env" << EOF
# Generated by setup.sh on $(date -Iseconds)
APP_ENV=production
DEBUG=false

# Application secrets
SECRET_KEY=${SECRET_KEY}
JWT_SECRET_KEY=${JWT_SECRET}

# Ports
API_PORT=8000
FRONTEND_PORT=3000
NGINX_PORT=80

# PostgreSQL (superuser — provisioning only)
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_USER=yoohoo
POSTGRES_PASSWORD=${PG_PASSWORD}
POSTGRES_DB=ps_core_db

# PostgreSQL (runtime app user — via PgBouncer)
POSTGRES_APP_USER=yoohoo_app
POSTGRES_APP_PASSWORD=${PG_APP_PASSWORD}

# PgBouncer
PGBOUNCER_HOST=pgbouncer
PGBOUNCER_PORT=6432
USE_PGBOUNCER=true

# Redis
REDIS_HOST=redis
REDIS_PORT=6379

# JWT
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
JWT_REFRESH_TOKEN_EXPIRE_DAYS=7

# CORS
CORS_ORIGINS=https://app.${DOMAIN}

# SMTP (configure with production provider)
SMTP_HOST=localhost
SMTP_PORT=587
SMTP_FROM=noreply@${DOMAIN}
SMTP_USE_TLS=true

# Frontend
FRONTEND_URL=https://app.${DOMAIN}

# Platform
PLATFORM_NAME=Yoohoo
PLATFORM_NAME_SHORT=Yoohoo
PLATFORM_URL=https://${DOMAIN}

# Email verification
EMAIL_VERIFICATION_EXPIRE_HOURS=48
UNVERIFIED_CLEANUP_DAYS=7

# Rate limiting
RATE_LIMIT_PER_MINUTE=60

# Invitations
INVITATION_EXPIRE_HOURS=72

# Password reset
PASSWORD_RESET_EXPIRE_MINUTES=30

# 2FA
TOTP_ISSUER_NAME=Yoohoo

# Sessions
MAX_ACTIVE_SESSIONS=10

# arq worker
ARQ_REDIS_DB=1
ARQ_MAX_JOBS=10
ARQ_JOB_TIMEOUT=300

# Logging
LOG_LEVEL=INFO
LOG_FORMAT=json

# Monitoring
GRAFANA_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

# Sentry (optional)
SENTRY_DSN=

# Backup offsite (optional — Hetzner Storage Box)
BACKUP_REMOTE=

# Docker image tag (set by CI/CD, not manually)
IMAGE_TAG=latest
EOF

  chmod 600 "$APP_DIR/.env"
  log ".env generated"
fi

# ─── Step 4: PgBouncer userlist ───
source "$APP_DIR/.env"
log "Updating PgBouncer userlist..."
cat > "$APP_DIR/pgbouncer/userlist.txt" << EOF
"${POSTGRES_USER}" "${POSTGRES_PASSWORD}"
"${POSTGRES_APP_USER:-yoohoo_app}" "${POSTGRES_APP_PASSWORD:-$POSTGRES_PASSWORD}"
EOF
chmod 600 "$APP_DIR/pgbouncer/userlist.txt"

# Guard: verify placeholders are gone
if grep -q "REPLACE_VIA_SETUP_SH" "$APP_DIR/pgbouncer/userlist.txt"; then
  fail "PgBouncer userlist still contains placeholders — .env may be incomplete"
fi

# ─── Step 5: Generate backup encryption key ───
if [ ! -f "$APP_DIR/.backup-key" ]; then
  openssl rand -base64 32 > "$APP_DIR/.backup-key"
  chmod 600 "$APP_DIR/.backup-key"
  log "Backup encryption key generated"
fi

# ─── Step 6: Pull images from GHCR ───
log "Logging into GHCR..."
DOCKER_CONFIG_DIR="$(mktemp -d)"
export DOCKER_CONFIG="$DOCKER_CONFIG_DIR"
echo "$GHCR_TOKEN" | docker login ghcr.io -u deploy --password-stdin

log "Pulling Docker images..."
IMAGE_TAG="${IMAGE_TAG:-latest}" docker compose pull api frontend
docker compose pull postgres pgbouncer redis nginx

# Cleanup GHCR credentials
rm -rf "$DOCKER_CONFIG_DIR"
unset DOCKER_CONFIG
log "GHCR credentials cleaned up"

# ─── Step 7: Start services ───
log "Starting services..."
IMAGE_TAG="${IMAGE_TAG:-latest}" docker compose up -d

# ─── Step 8: Wait for PostgreSQL ───
log "Waiting for PostgreSQL..."
for i in $(seq 1 30); do
  if docker compose exec -T postgres pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" 2>/dev/null; then
    break
  fi
  sleep 2
done

# ─── Step 9: Create app role (DB privilege separation) ───
log "Setting up database roles..."
docker compose exec -T postgres psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "
  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_APP_USER:-yoohoo_app}') THEN
      CREATE ROLE \"${POSTGRES_APP_USER:-yoohoo_app}\" WITH LOGIN PASSWORD '${POSTGRES_APP_PASSWORD:-$POSTGRES_PASSWORD}' NOSUPERUSER NOCREATEDB;
      GRANT CONNECT ON DATABASE \"$POSTGRES_DB\" TO \"${POSTGRES_APP_USER:-yoohoo_app}\";
    END IF;
  END \$\$;
" 2>/dev/null || warn "Role creation skipped (may already exist)"

# ─── Step 10: Run central migrations ───
log "Running central database migrations..."
docker compose exec -T api alembic -x mode=central upgrade central@head

# ─── Step 11: Seed database ───
log "Seeding database..."
mkdir -p "$SECRETS_DIR"
chmod 700 "$SECRETS_DIR"

docker compose exec -T \
  -e SEED_ADMIN_EMAIL="$ADMIN_EMAIL" \
  -e SEED_ADMIN_PASSWORD="$ADMIN_PASSWORD" \
  -e SEED_OUTPUT_FILE="/app/seed-output.tmp" \
  api python scripts/seed.py

# Copy seed output to host secrets dir
docker compose cp api:/app/seed-output.tmp "$SECRETS_DIR/seed-credentials" 2>/dev/null || true
chmod 600 "$SECRETS_DIR/seed-credentials" 2>/dev/null || true

# ─── Step 12: SSL Certificate ───
log "Initializing SSL certificate..."
if [ -f "$APP_DIR/ssl/fullchain.pem" ]; then
  warn "SSL certificates already exist — skipping"
else
  # Stop nginx temporarily for standalone cert request
  docker compose stop nginx

  certbot certonly --standalone --non-interactive --agree-tos \
    --email "$ADMIN_EMAIL" \
    --cert-name yoohoo \
    -d "$DOMAIN" \
    -d "www.$DOMAIN" \
    -d "app.$DOMAIN" \
    || fail "Certbot failed — check DNS records"

  # Copy certs
  cp /etc/letsencrypt/live/yoohoo/fullchain.pem "$APP_DIR/ssl/"
  cp /etc/letsencrypt/live/yoohoo/privkey.pem "$APP_DIR/ssl/"
  chmod 644 "$APP_DIR/ssl/fullchain.pem"
  chmod 600 "$APP_DIR/ssl/privkey.pem"

  # Restart nginx with SSL
  IMAGE_TAG="${IMAGE_TAG:-latest}" docker compose up -d nginx
  log "SSL certificate installed"
fi

# ─── Step 13: Start monitoring ───
log "Starting monitoring stack..."
docker compose -f monitoring/docker-compose.monitoring.yml up -d 2>/dev/null || warn "Monitoring start failed"
docker compose -f monitoring/docker-compose.collector.yml up -d 2>/dev/null || warn "Collector start failed"

# ─── Step 14: Health check ───
log "Running health check..."
for i in 1 2 3 4 5; do
  if curl -sf http://localhost/health/ready > /dev/null 2>&1; then
    break
  fi
  sleep 5
done

# ─── Summary ───
echo ""
echo "=========================================="
echo "  Yoohoo Setup Complete"
echo "=========================================="
echo ""
echo "  Marketing site: https://${DOMAIN}"
echo "  Application:    https://app.${DOMAIN}"
echo "  API docs:       https://app.${DOMAIN}/docs (disabled in prod)"
echo ""
echo "  Grafana:        http://localhost:3000 (via SSH tunnel)"
echo "  Uptime Kuma:    http://localhost:3001 (via SSH tunnel)"
echo ""
echo "  Admin email:    ${ADMIN_EMAIL}"
echo "  Credentials:    ${SECRETS_DIR}/seed-credentials"
echo ""
echo "  Next steps:"
echo "    1. Configure GitHub Secrets (VPS_HOST, VPS_SSH_KEY, etc.)"
echo "    2. Configure SMTP provider in .env"
echo "    3. Set up Uptime Kuma monitors"
echo "    4. Test backup: bash scripts/backup/backup.sh"
echo ""
echo "=========================================="
